<?php
    switch ($error) {
    	
        case 'ERROR_NOMBRE': ?>
			EL NOMBRE DE USUARIO ESTA ERRADO. POR FAVOR, VERIFICALO.
			<br />
			SI NO LO RECUERDAS, CONTACTA CON EL ADMINISTRADOR DEL SISTEMA.
<?php		break;
			
        case 'ERROR_CLAVE': ?>
			LA CLAVE ESCRITA ESTA ERRADA. POR FAVOR, VERIFICALA.
			<br />
			SI NO LA RECUERDAS, CONTACTA CON EL ADMINISTRADOR DEL SISTEMA.
<?php		break;
			
        case 'ERROR_NOMBRE_INACTIVO': ?>
			EL NOMBRE DE USUARIO DIGITADO ESTA INACTIVO. 
			<br />
			POR FAVOR, CONTACTA CON EL ADMINISTRADOR DEL SISTEMA.
<?php		break;
			
        case 'ERROR_EMPRESA_INACTIVA': ?>
			LA EMPRESA CON EL CODIGO DIGITADO NO ESTA ACTIVA.
			<br />
			POR FAVOR, CONTACTA CON EL DEPARTAMENTO DE VENTAS PARA VERIFICAR EL ESTADO DE TU CUENTA.
<?php		break;        

		case 'ERROR_NOMBRE_EMPRESA': ?>
			EL NOMBRE DE LA EMPRESA ESTA ERRADO. POR FAVOR, VERIFICALO.
			<br />
			SI NO LO RECUERDAS, CONTACTA CON EL ADMINISTRADOR DEL SISTEMA.
<?php		break;

        default: ?>
			NO ENTIENDO EL RESULTADO QUE SE ME ENVIO.
			<br />
			URGENTE, CONTACTA CON EL ADMINISTRADOR DEL SISTEMA.
<?php		break;
    }
?>






